### ISSUE TITLE
Not deleting files when removing a torrent

### ISSUE THREAD

**Issue by Angristan** [jfurrow/flood#158] opened 2016-10-25 09:21 UTC
Hello,

when I remove a torrent and tick "delete data", it does not actually delete the files.

Is it a bug or is it on my side ?

**Comment by Angristan** [comment] 2016-10-25 09:35
It appears to be random, I'll update if it happens again

**Comment by Angristan** [comment] 2016-11-21 20:59
Still happens.

**Comment by jfurrow** [comment] 2016-11-24 07:22
@Angristan I've noticed this also, sometimes the `d.base_path=` response from rTorrent is an empty string, which is what Flood uses to determine the path of the torrent. I need to figure out why this happens.

**Comment by wopian** [comment] 2017-03-06 01:05
From what i've noticed from my current usage, torrents manually added via Flood will have their files correctly removed when deleted.

Files added via RSS within Flood however, will not have their files removed when deleted.

**Comment by blackjelly** [comment] 2017-03-06 15:50
I encountered the same problem. All the downloads are manually added by the file, prompted to delete the success, but the file still exists.

**Comment by jfurrow** [comment] 2017-03-09 04:25
Thanks @wopian and @blackjelly for the details. That is an interesting quirk. This is the next issue I'll work on.

**Comment by jfurrow** [comment] 2017-03-10 05:14
Thanks for your patience, everyone. I am fairly certain this is fixed, but please re-open if you run into this issue again.

**Comment by wopian** [comment] 2017-03-10 05:34
git pulled and restarted flood. deleted several torrents added via RSS and their files remained in the downloads directory with a success message.

![](http://i.imgur.com/D3njDmw.png)
![](http://i.imgur.com/rE0yVFe.png)
![](http://i.imgur.com/2jo6VgI.png)
![](http://i.imgur.com/Vzhq127.png)
![](http://i.imgur.com/7KibHGG.png)
![](http://i.imgur.com/Nja1j0t.png)

**Comment by jfurrow** [comment] 2017-03-10 06:54
@wopian Thanks for the prompt update. Would you mind helping me by checking out the branch `bug/fix-torrent-data-deletion-debug`, then trying the same thing and providing the output from the Node server here? It should output the paths it's trying to delete. Sorry, this is crude, but I'm struggling to reproduce this.

**Comment by wopian** [comment] 2017-03-10 07:08
@jfurrow unfortunately I got neither of the 3 possible logs.

**Comment by jfurrow** [comment] 2017-03-10 07:11
@wopian I just pushed another commit, could you `git pull` and try again? Thanks for your help... something is definitely awry.

**Comment by wopian** [comment] 2017-03-10 07:16
Actually, it was my own mistake. I run Flood behind screen, so was only looking at the browser's console output. Turns out it was only logging to the terminal's console. Got the following output without file being deleted:

```bash
Should delete data: true
Selected hashes: 70CBCD1957BFECF4BBB9A5C8460A5B793EC8AF61
Attempting to delete file: /opt/rtorrent/download/[HorribleSubs] Koro-sensei Quest! - 12 [480p].mkv
```

**Comment by jfurrow** [comment] 2017-03-10 07:21
Alright, we're getting somewhere... I pushed yet another commit, would you mind repeating the process?

**Comment by wopian** [comment] 2017-03-10 07:22
```bash
Should delete data: true
Selected hashes: 70CBCD1957BFECF4BBB9A5C8460A5B793EC8AF61
Attempting to delete file: /opt/rtorrent/download/[HorribleSubs] Koro-sensei Quest! - 12 [480p].mkv
POST /api/client/torrents/delete 200 47.903 ms - 5
Deleted files:

GET ...
```

**Comment by jfurrow** [comment] 2017-03-10 07:23
Does the user account running the Flood process have access to this directory?

**Comment by jfurrow** [comment] 2017-03-10 07:25
I pushed another commit... could you please repeat? Thanks again, I really appreciate the help.

**Comment by wopian** [comment] 2017-03-10 07:36
>Does the user account running the Flood process have access to this directory?

Mhmm. Thought I had both users under the same group. Only rtorrent user had permissions for the folder. Both are now in the same group which has read/write permissions on `/opt/rtorrent/download`.

Although I get the same output in the end 😭😭

```bash
Should delete data: true
Selected hashes: 70CBCD1957BFECF4BBB9A5C8460A5B793EC8AF61
Files to delete:
/opt/rtorrent/download/[HorribleSubs] Koro-sensei Quest! - 12 [480p].mkv
POST /api/client/torrents/delete 200 73.870 ms - 5
Deleted files:

GET /api/client/torrents 200 20.076 ms - -
```

```bash
Should delete data: true
Selected hashes: 9E20E036F4D963A16F363BE31AF413EBD5805A41
Files to delete:
/opt/rtorrent/download/[orz] Sansha Sanyou 09 [Dual-Audio Patch].zip
POST /api/client/torrents/delete 200 46.784 ms - 5
Deleted files:

GET /api/client/torrents 200 17.949 ms - -
```

**Comment by jfurrow** [comment] 2017-03-10 07:41
Alright, I've got to sign off for now, but I'll come back to this tomorrow. Thank you _so much_ for the help, I greatly appreciate it. ❤️ Sorry you're still experiencing this issue. I'll try to create an environment similar to yours tomorrow, if you can think of any more relevant details (I can't right now), please provide them.

If any other users in can reproduce the issues @wopian's experiencing, please provide any relevant details.

**Comment by wopian** [comment] 2017-03-10 11:05
It seems it might be an issue with torrents downloaded via a [specific](https://shanaproject.com) source (RSS and magnets from it consistently fail to delete). Another file from another source that was around 300 mb succedded:

```
Should delete data: true
Selected hashes: 9361A867816C567927F57A253FB4312D71E246CC
Files to delete:
/opt/rtorrent/download/[Maid-chan] RADWIMPS - Kimi no Na wa. (Original Soundtrack) (FLAC)
POST /api/client/torrents/delete 200 56.202 ms - 5
Deleted files:
/opt/rtorrent/download/[Maid-chan] RADWIMPS - Kimi no Na wa. (Original Soundtrack) (FLAC)
```

**Comment by jfurrow** [comment] 2017-03-11 04:04
@wopian This should actually be fixed by https://github.com/jfurrow/flood/pull/289. Please test and let me know. Thanks!

**Comment by wopian** [comment] 2017-03-11 05:04
@jfurrow successfully deleted all the files 🎉🎉🎉

**Comment by jfurrow** [comment] 2017-03-11 07:46
Thanks for all your help ❤️

**Closed** 2017-03-11 07:46 UTC
Labels: bug

**Comment by JohnFlowerful** [comment] 2017-06-25 00:13
Gonna bump this. 
Is it possible to delete the *empty* directories left over from the torrents?

**Comment by jfurrow** [comment] 2017-07-09 21:59
@JohnFlowerful Created another issue for that: https://github.com/jfurrow/flood/issues/399
