### ISSUE TITLE
Deleting torrents leaves empty folder

### ISSUE THREAD

**Issue by valdearg** [jfurrow/flood#466] opened 2017-10-12 21:26 UTC
When deleting a torrent which results in a folder, the root folder remains empty.

E.g. Downloads/Torrent1/File 1, File 2, File 3

If you delete the torrent within Flood, all content will be removed but the empty Torrent1 folder will remain.

Latest version from git updated today, running on Ubuntu Server 16.04. Node version 6.9.5.

**Comment by Jeoffreybauvin** [comment] 2017-10-13 06:47
Same problem here.

**Comment by jfurrow** [comment] 2017-10-23 05:53
Yeah, this should be handled better.

**Comment by noraj** [comment] 2018-05-20 13:54
duplicate of #399

**Closed by noraj** 2018-05-20 13:54 UTC
Labels: duplicate, enhancement
