### ISSUE TITLE
Deleted file failed

### ISSUE THREAD

**Issue by blackjelly** [jfurrow/flood#285] opened 2017-03-06 11:15 UTC
When deleting files and data, the operation is successful, but the files on the server still exist.

**Comment by wopian** [comment] 2017-03-06 13:31
See https://github.com/jfurrow/flood/issues/158

**Comment by jfurrow** [comment] 2017-03-09 03:57
I'm closing this as a duplicate of #158, but will work on a solution ASAP.

**Closed by jfurrow** 2017-03-09 03:57 UTC
