### ISSUE TITLE
Progress bar inconsistent height

### ISSUE THREAD

**Issue by sachaw** [jfurrow/flood#517] opened 2017-11-05 09:18 UTC
Proof:
![proof](https://user-images.githubusercontent.com/11172820/32139668-b9edb8c6-bc97-11e7-8fce-cd1919e4147e.png)
OS:
Win 10 Pro Insider Preview, Build 17025
Browser: Chrome Canary Version 64.0.3259.0 64Bit

**Comment by dcousens** [comment] 2017-11-05 12:02
Can reproduce in `Chromium 62.0.3202.75`,  but only at odd zoom levels.

**Comment by wopian** [comment] 2017-11-05 17:05
Unable to reproduce in the following browsers with Windows 10 Pro 1709

- [Chrome 61](https://i.imgur.com/pmJ2u1n.png)
- [Chrome 64](https://i.imgur.com/0eoq8EG.png)
- [Firefox 56](https://i.imgur.com/Nz6sqG0.png)

**Comment by dcousens** [comment] 2017-11-06 00:19
@wopian wow,  disabling hardware acceleration locally did **not** help the situation.

![what](https://user-images.githubusercontent.com/413395/32420789-3f209a98-c2e4-11e7-9572-ee46e1b55820.png)

The progress bar is still visual,  but with hardware accel disabled,  the page struggles to render at all.  The majority of the text/DOM appears to be missing...

**Comment by dcousens** [comment] 2017-11-06 00:22
@jfurrow I notice you use a lot of GPU accelerated features, `transform` etc.  Maybe that is the root cause?

**Comment by dcousens** [comment] 2017-11-06 00:25
@sachaw it may be notable that it is every 2nd row, after the top 3, for me.

**Comment by sachaw** [comment] 2017-11-06 07:04
can we confirm that this is not resolution related, I've tested on 1920*1080 and 1440*900, same result

**Comment by dcousens** [comment] 2017-11-06 07:30
2560x1440

**Comment by jfurrow** [comment] 2017-11-07 05:05
@dcousens I agree, it seems likely due to GPU compositing layers. That's the only thing that would cause these inconsistencies.

@sachaw I noticed you're running this with experimental/beta releases (Win 10 insider preview and Chrome Canary). I suspect this is the root of the problem. Have you tried on stable releases?

**Comment by sachaw** [comment] 2017-11-07 06:07
@jfurrow yes, That's just what I was on at the time of posting, Have tried with chrome stable and windows 10 pro

**Comment by dcousens** [comment] 2017-11-07 10:33
@jfurrow understandably,  this bug does not appear to be a flood problem.
However,  I think it is still within our interest to keep the issue open and resolve the problem,  even if the root cause is upstream.

**Comment by jfurrow** [comment] 2017-11-11 03:12
@dcousens That's reasonable! Thanks for helping with the housekeeping on these issues.

**Comment by jfurrow** [comment] 2017-11-11 03:13
@sachaw I'd love for you to test https://github.com/jfurrow/flood/pull/528!

**Comment by jfurrow** [comment] 2017-11-12 20:43
@sachaw I just merged the PR and I'm fairly confident it will fix your rendering issues. When testing, remember to rebuild static assets (`npm run build`).

**Closed** 2017-11-12 20:42 UTC
