### ISSUE TITLE
Sidebar stats should show 0 instead of NaN

### ISSUE THREAD

**Issue by vBm** [jfurrow/flood#55] opened 2016-06-28 11:27 UTC
This is rather a minor thing.
On fresh start, instead of showing real number we get NaN.

![2016-06-28_13-24-39](https://cloud.githubusercontent.com/assets/80596/16413720/fada879a-3d33-11e6-9d93-b8fc3bba6b31.png)

edit: silly me, switching the two in title xD

**Comment by jfurrow** [comment] 2016-07-01 03:04
Agreed, should handle this better. Stay tuned...

**Comment by jfurrow** [comment] 2017-02-04 18:09
Honestly I'm not sure if I inadvertently fixed this a while ago, but I can't reproduce it on a fresh install so I'm labelling it as such and closing. Please re-open if you see this again!

**Closed by jfurrow** 2017-02-04 18:09 UTC
Labels: bug

**Comment by vBm** [comment] 2017-02-04 20:19
Yeah, It's fixed 👍 
Thanks xD
