### ISSUE TITLE
Flood database corruption

### ISSUE THREAD

**Issue by mirolm** [jfurrow/flood#490] opened 2017-10-21 07:29 UTC
One time i managed to break flood settings database. It took several setting changes and page refreshes to do so. When this happened flood refused to load and i needed to reinstall. I will try to reproduce this and see when and how it happens.

Will it be better to use some file database like SQLite for example instead of json flat files to store the application settings and data?

**Comment by dcousens** [comment] 2017-10-21 22:37
Maintaining `sql` schema is annoying.
I don't think the database "type" is important,  so much as whether it supports atomic operations to avoid corruption.

**Comment by jfurrow** [comment] 2017-10-23 05:42
@mirolm Sorry you're having problems, but unfortunately this issue isn't actionable, so I'll have to close it. Pleas reopen if you can provide steps to reproduce the problem.

Right now Flood uses [nedb](https://github.com/louischatriot/nedb), which has been working really well. It's nice because it can be installed via `npm` with no external dependencies. While Flood continues to store small amounts of data, I think nedb is the right choice.

**Closed by jfurrow** 2017-10-23 05:42 UTC
