### ISSUE TITLE
API error 401 for remote user on first time

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#208] opened 2017-01-03 22:49 UTC
Hi,

I installed nvm and nodejs as a user (install in home directory) on my dedicated server.
I cloned flood in my user home directory.
I configured flood and started it.
As it is installed on my remote server, I need to do a local port forwarding via ssh to test flood (in order to avoid a web server proxy at teh beginning): `ssh user@example.org -L 3000:localhost:3000`.
And then on my guest I can access to flood web interface.
Nice, I start creating a user and wait.
I can see on the server console that flood is getting HTTP 401 error (Unantorized access) from the API.

```
$ npm run start:production  

> flood@0.0.0 start:production /home/sdbox/flood
> npm run prestart; node ./server/bin/www


> flood@0.0.0 prestart /home/sdbox/flood
> NODE_ENV=production gulp dist

[22:52:44] Using gulpfile ~/flood/gulpfile.js
[22:52:44] Starting 'webpack'...
[22:52:44] Starting 'sass'...
[22:52:44] Starting 'images'...
[22:52:50] Finished 'sass' after 5.79 s
[22:52:50] Starting 'minify-css'...
[22:53:07] Finished 'minify-css' after 17 s
[22:54:32] [webpack] Hash: 140664a33f1dd0c99f24
Version: webpack 1.14.0
Time: 108096ms
                      Asset     Size  Chunks             Chunk Names
    ./server/assets//app.js  3.68 MB       0  [emitted]  main
./server/assets//app.js.map  4.44 MB       0  [emitted]  main
[22:54:32] Finished 'webpack' after 1.8 min
[22:54:32] Starting 'minify-js'...
[22:56:18] Finished 'minify-js' after 1.75 min
[22:56:18] Finished 'images' after 3.57 min
[22:56:18] Starting 'default'...
[22:56:18] Finished 'default' after 130 μs
[22:56:18] Starting 'dist'...
[22:56:18] Finished 'dist' after 27 μs
removed 0 entries from daySnapshot
removed 0 entries from monthSnapshot
removed 0 entries from thirtyMinSnapshot
removed 0 entries from fiveMinSnapshot
removed 0 entries from hourSnapshot
removed 0 entries from weekSnapshot
GET / 200 1772.957 ms - 184
GET /style.css 200 33.677 ms - -
GET /favicon.ico 200 112.468 ms - 184
GET /favicon.ico 200 82.811 ms - 184
GET /style.css 304 8.804 ms - -
GET / 304 192.534 ms - -
GET /style.css 304 13.024 ms - -
GET /app.js 200 14.372 ms - -
GET /auth/verify?1483480665657 200 7.818 ms - 20
POST /auth/register 200 999.963 ms - 20
GET /api/history?snapshot=fiveMin 401 55.865 ms - -
GET /api/stats 401 3.937 ms - -
GET /api/notifications?limit=10&start=0 401 2.313 ms - -
GET /api/client/torrents 401 3.201 ms - -
GET /api/client/settings 401 1.262 ms - -
GET /api/settings 401 1.181 ms - -
GET /api/history?snapshot=fiveMin 401 2.028 ms - -
GET /api/stats 401 2.136 ms - -
GET /api/notifications?limit=10&start=0 401 1.990 ms - -
GET /api/client/torrents 401 3.564 ms - -
GET /api/history?snapshot=fiveMin 401 4.664 ms - -
GET /api/stats 401 3.430 ms - -
GET /api/notifications?limit=10&start=0 401 6.574 ms - -
GET /api/client/torrents 401 5.886 ms - -
GET /api/history?snapshot=fiveMin 401 3.027 ms - -
GET /api/stats 401 1.048 ms - -
GET /api/notifications?limit=10&start=0 401 1.004 ms - -
GET /api/client/torrents 401 1.951 ms - -
GET /api/history?snapshot=fiveMin 401 1.844 ms - -
GET /api/stats 401 1.941 ms - -
GET /api/notifications?limit=10&start=0 401 2.144 ms - -
GET /api/client/torrents 401 4.253 ms - -
GET /api/history?snapshot=fiveMin 401 3.523 ms - -
GET /api/stats 401 0.961 ms - -
GET /api/notifications?limit=10&start=0 401 1.983 ms - -
GET /api/client/torrents 401 1.991 ms - -
GET /api/history?snapshot=fiveMin 401 3.081 ms - -
GET /api/stats 401 1.848 ms - -
[...]
```

By stopping all and trying again the same way:
When arriving on the authentification page user has been created (no more create button but a log in button), I log in with the previously created credentials (when it was buggy) and now it works and I can see teh API is responding on the server console.

So this bug is only occuring the first time after install.

---

Out-topic question: when running flood `npm run start:production`, is it possible to avoid recompiling all css, doing snapshot, minifying js and all... I mean we just want to launch the web server because it is currently during about 5 minutes to start flood.

**Comment by jfurrow** [comment] 2017-01-05 03:38
Thanks @noraj1337, I'll look into this ASAP.

Regarding the asset compilation, I totally agree, and plan to remove it entirely by committing the compiled assets to the repo.

**Comment by jfurrow** [comment] 2017-01-06 05:33
@noraj1337 After more thoroughly reading your reproduction steps, I'm 99% sure this is not a bug.

The 401 response from the server on initial load is expected and not a bug. When you are not authenticated, Flood returns a 401 unauthorized status. If there are no user accounts present, it will prompt you to create one. This is working as expected.

I'm going to close this issue, but please re-open if the process I described is not working for you.

In regards to the asset compilation, that will be changed in #215.

**Closed by jfurrow** 2017-01-06 05:33 UTC
Labels: bug

**Comment by noraj1337** [comment] 2017-01-07 09:58
I think I understand, the API return 401 until a user is login. Thanks

**Comment by jfurrow** [comment] 2017-01-13 05:25
That's correct. The Flood UI handles the 401 error gracefully (by prompting for login) and is expected behavior.

Thanks for the issue!

**Comment by noraj1337** [comment] 2017-01-15 12:41
At first use you are redirected on the **register** page and then on the **list** page after accont creation.
But you stay indefinitely on the **list** page. You have to manually select the **login** page or realod the interface on the root of the web server to be redirected to the **login** page.

**Comment by sanpoChew** [comment] 2017-03-01 16:39
Just to add, this just happened to me too. After registering a list appears with a couple of boxes ticked. It appears as though it was loading but looking at the output from the server it was just 403ing the same requests over and over. Refreshing the page brought me to a login page and after logging in everything seems to work.
