### ISSUE TITLE
High CPU usage when there is a notification

### ISSUE THREAD

**Issue by whtv** [jfurrow/flood#438] opened 2017-08-26 09:00 UTC
In Firefox, when displaying the flood interface, I normally get 6–7 % CPU usage (with only a handful of torrents). However, as soon as there is any notification, as indicated by the notifications symbol, CPU usage goes up to around 40 %; it goes down to 6–7 % again as soon as I clear the notifications.

**Comment by randomnonsense** [comment] 2017-08-26 22:45
Works here fine. Try with "hardware acceleration" on and off and see if that help. It's been traditionally broken for years now. Anyhow, this is a problem for mozilla's developers. Firefox is a slow and bloated browser. Not the first time something doesn't work right. Compare with newest Chromium. If Chromium works fine, it's either your system (e.g. problem with actual hardware accel) or firefox in itself.

**Comment by whtv** [comment] 2017-08-30 10:00
If you're talking about a hardware acceleration option in firefox, I don't have that option (v 55). Firefox in safe-mode has the same issue. Chromium however works fine.

**Comment by randomnonsense** [comment] 2017-08-31 16:35
In Firefox, see Tools > Options > Advanced > General, and there under "Browsing" should be an option "Use hardware acceleration when available". Try with this one checked and unchecked.

Second, be advised that many FF plugins can be slowing you down, especially those which may have to do anything with javascript or similar code, like Adblock, Noscript etc. Try whitelisting flood everywhere.

**Comment by whtv** [comment] 2017-09-04 22:01
I really don't have that option in 55, and I do remember seeing it before. I like your suggestion about switching to Chromium; why not, I'll try it. Issue can be closed as far as I'm concerned, it seems to be a Firefox issue primarily.

**Comment by jfurrow** [comment] 2017-10-23 06:22
I've not been able to reproduce this — @whtv can you try the latest build, please?

**Comment by noraj** [comment] 2018-05-20 13:42
In general flood acts bad with Firefox because until now @jfurrow designed it only with chrome (see discussion in #579).

So I'm closing this issue as duplicate of the more general #224

**Closed by noraj** 2018-05-20 13:42 UTC
Labels: can't reproduce, performance
