### ISSUE TITLE
Torrents Not Removed

### ISSUE THREAD

**Issue by g00sed** [jfurrow/flood#772] opened 2019-03-13 05:40 UTC
When I remove a torrent and choose to have its data removed as well, the data remains in the downloads folder without change, but its listing disappears from the client.

edit: I fixed this behavior by running rtorrent and flood with the same user. Now the issue is that deleted torrents leave behind an empty folder.

**Comment by noraj** [comment] 2019-03-16 14:15
- data not being removed: this permission issue and this is the normal behavior if you didn't get flood the right access, see https://github.com/jfurrow/flood/wiki/Install-flood-with-a-service-account
- empty folder: duplicate of https://github.com/jfurrow/flood/issues/399

**Closed by noraj** 2019-03-16 14:15 UTC

**Comment by noraj** [comment] 2019-03-16 14:17
Also for the next time you open an issue, here it what I will answer you:

> Thanks for posting your issue, but can you please take time to edit it in order to fill the issue template. Those information is very important for the developer else he won't be able to reproduce anything.

```markdown
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.
- [ ] Please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [ ] Please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version:
  + Node.js version `node --version`
  + npm version `npm --version`
  + Web browser `name and version`
* Operating System and version:

## Summary
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- (Optional) Tell us what should happen -->

## Current Behavior
<!--- (Optional) Tell us what happens instead of the expected behavior -->

## Possible Solution
<!--- (Optional) suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- (Optional) What are you trying to accomplish? -->
```

> I'm closing the issue until you fill it.
>
> Feel free to ask to re-open it as soon as it's done.
