### ISSUE TITLE
Communication with rtorrent via socket not working after #638

### ISSUE THREAD

**Issue by randomnonsense** [jfurrow/flood#703] opened 2018-09-03 22:23 UTC
Hello, 

Just pulled recent updates from git. So far I've always had in my config.js:

> scgi: {
>     socket: true,
>     socketPath: '/home/rtorrent/rtorrent.socket'
>   },

which has worked just fine. Now, after commenting that out, and trying the same path with the configurator, it doesn't work. Re-setting rtorrent to TCP at scgi_port:ip:port works fine.

This cannot be my config since I've just been running older flood on that socket for literally a year. Please advice.

**Comment by jfurrow** [comment] 2018-09-04 00:27
I'm sure I broke this, will fix ASAP.

**Comment by jfurrow** [comment] 2018-09-04 00:59
Fixed in https://github.com/jfurrow/flood/pull/705

**Comment by noraj** [comment] 2018-09-15 14:34
`config.template.js` is lacking of this part right ?

It was accidentally removed ?

```javascrit
   // Configuration details for your backend rtorrent interface.
   // These are defaults for most installs; check your .rtorrent.rc for changes.
   scgi: {
     host: 'localhost',
     port: 5005,
     socket: false,
     socketPath: '/tmp/rtorrent.sock'
   },
```

@jfurrow Please keep the changelog up to date so we can know what changed.

**Comment by noraj** [comment] 2018-09-15 16:14
And also how how to move from a TCP to Unix socket ?

**Comment by jfurrow** [comment] 2018-09-15 18:14
@noraj Those values are stored in the user database now.

**Comment by jfurrow** [comment] 2018-09-15 18:15
> And also how how to move from a TCP to Unix socket ?

Close rtorrent, open Flood and you'll be prompted to change connection method via the UI. Should add ability to update user in the future.

**Comment by jfurrow** [comment] 2018-09-15 18:16
Not sure why this was reopened, the issue is fixed

**Closed** 2018-09-15 18:16 UTC
Labels: question

**Comment by noraj** [comment] 2018-09-17 18:58
@jfurrow But the user also need to change his `.rtorrentrc` config (`scgi_port = 127.0.0.1:5000`) and reverse proxy (ex: nginx `proxy_pass` + rewrite rule) config ?

**Comment by zawapete** [comment] 2018-09-17 19:03
@noraj obviously flood setup must match rtorrent setup: if rtorrent scgi is on network, socket connection won't work, and viceversa. at the contrary no change is needed on nginx side as proxy for changing scgi setup between flood and rtorrent
