### ISSUE TITLE
"Cannot connect to rTorrent" loop on latest master

### ISSUE THREAD

**Issue by etbusch** [jfurrow/flood#706] opened 2018-09-04 20:34 UTC
## Summary

The "Cannot connect to rTorrent" dialog pops up on app load and successfully tests the connection, and then proceeds to appear again when save is pressed.

## Expected Behavior

The app should take the xmlrpc server information, save it, and continue loading the app.

## Current Behavior

The "Cannot connect to rTorrent" dialog pops up and prompts me to enter in the ip and port the rtorrent xmlrpc server is listening on

I enter in the correct info and click "Test", and a checkmark appears.

I click submit, the dialog disappears momentarily, but then reappears with the information populated in the form.

This was working before I updated, and ruTorrent is currently working fine with the same rtorrent server. I reinstalled flood from scratch as well (with a fresh config.js) with the same result.

## Possible Solution

Fix the bug, and perhaps be a little less strict on issue templates ;)

## Steps to Reproduce (for bugs)

1. install flood
2. use a TCP connection to the rtorrrent xmlrpc server
3. attempt to use the app
4. 

## Context

This prevents the use of flood entirely on my setup

## Your Environment

* Version used: e21ab29c8ed10a600ca316fb7e8a88006c5ca512
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodeJS 8.9.2
* Operating System and version: Alpine Linux 3.7

**Comment by Roguyt** [comment] 2018-09-04 20:38
Quoting @jfurrow on Discord, since i was having the same issue

> 8:50 PM] jfurrow: so in your case it's going to try to use the socket because it's not an empty string
[8:50 PM] jfurrow: sorry I'm not able to fully help but if you have access to the users db at server/db/users.db you can modify it directly, jsut remove the socketPath property on the user
[8:51 PM] jfurrow: then restart the Flood server and it should just work
[8:51 PM] jfurrow: I'll have to fix this later

**Comment by etbusch** [comment] 2018-09-04 20:58
There aren't any properties named "socketPath" in the entries in users.db on my install.

**Comment by Roguyt** [comment] 2018-09-04 21:05
Oh.
Well guess you'll have to wait for a reply from the team.

**Comment by rkkoszewski** [comment] 2018-09-05 09:20
Same issue here inside a LXC container with the same setup: OS: Alpine Linux 3.7 NodeJS: 8.9.2 and latest commit.

**Comment by noraj** [comment] 2018-09-06 17:30
PS : @etbusch I know I'm boring but please respect the issue template next time ;)

**Comment by etbusch** [comment] 2018-09-06 20:30
@noraj yes, you are boring.

**Comment by bbashy** [comment] 2018-09-07 09:54
Have you updated your `config.js` file with the `config.template.js` changes?

**Comment by Kiina** [comment] 2018-09-07 15:14
Deleted all my db files, removed scgi from config.js but I still have the same issue

**Comment by bbashy** [comment] 2018-09-07 15:15
@Kiina If you're doing all that, have you tried deleting the folder and re-cloning + setting up?

**Comment by Kiina** [comment] 2018-09-07 16:45
I recloned the repo into a new directory and did setup from beginning. Took a long time because it's a raspberry pi but the issue is still the same.


```
[kiina@raspberrypi flood]$ uname -r
4.14.68-1-ARCH
[kiina@raspberrypi flood]$ node -v
v10.1.0
[kiina@raspberrypi flood]$ npm -v
6.0.1
```

**Comment by Handyone** [comment] 2018-09-07 19:53
Same here, with every reboot, relogin or refresh I get cannot connect to rtorrent even when files downloading with rtorrent.
![cannot connect to rtorrent](https://user-images.githubusercontent.com/12858813/45240284-61564280-b2e8-11e8-8914-3db0d0f352f4.png)

**Comment by boistordu** [comment] 2018-09-12 13:30
I can confirm the result. 
OS: archlinux up-to-date

**Comment by etbusch** [comment] 2018-09-12 14:11
I also confirm that reverting to 3da1fbfc5a34212fb2955f04343af069c25bb0fe fixes the issue.

**Comment by jfurrow** [comment] 2018-09-15 05:44
Should be fixed by https://github.com/jfurrow/flood/commit/3e782b46e5f18e05273a577dd9648223838d493c

**Closed by jfurrow** 2018-09-15 05:44 UTC
Labels: bug
