### ISSUE TITLE
Contextual menu appears at the wrong place

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#551] opened 2017-11-27 18:37 UTC
When right clicking (opening the contextual menu) on a torrent at the bottom of the screen bottom of the screen the contextual menu appears on the top and is cropped (both on condensed or expended view).

## Expected Behavior

Opening the contextual menu at the bottom and not being cropped.

![](https://i.imgur.com/h8aSgs0.png)

## Current Behavior

When right clicking (opening the contextual menu) on a torrent at the bottom of the screen bottom of the screen the contextual menu appears on the top and is cropped.

![](https://i.imgur.com/oboZnYt.png)

## Possible Solution

Seems to appears both on Firefox and Opera so that does not seem to be a browser render bug but a flood bug.

## Steps to Reproduce (for bugs)

1. Right click on the last torrent

## Your Environment

* Version used:
  + Version (stable release) `v1.0.0`
  + Commit ID (development release) ` 2fd0edae15d21bcb79421b6ca1b07c9ff7705bc7`
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 57.0, Opera 49.0
* Operating System and version: Archlinux

**Comment by jfurrow** [comment] 2017-11-30 05:26
This was fixed by https://github.com/jfurrow/flood/pull/568

**Closed by jfurrow** 2017-11-30 05:26 UTC
Labels: bug, design

**Comment by dcousens** [comment] 2017-11-30 05:37
@noraj1337 duplicate of https://github.com/jfurrow/flood/issues/516#event-1364947971 :P

**Comment by noraj1337** [comment] 2017-11-30 09:15
@dcousens Yes, I looked into issues but you were calling the contextual menu _Right click menu_ so I didn't found your issue. Lol
