### ISSUE TITLE
Problem with nginx reverse proxy – serving same file regardless of URL 

### ISSUE THREAD

**Issue by NoLooseEnds** [jfurrow/flood#680] opened 2018-07-04 21:09 UTC
(This is a duplicate of an [issue](https://github.com/dperson/openvpn-client/issues/130) over at https://github.com/dperson/openvpn-client/, and I'm hoping someone here are able to spot the problem)

Hi, I'm having issues with getting the nginx reverse proxy to work.

I'm trying to serve the flood web interface from my rtorrent docker image. The rtorrent docker image get's the VPN ip, so that works.

I run:
`docker run -it --name web -p 80:80 -p 443:443 --link openvpn-client:rtorrent -d dperson/nginx -w "http://rtorrent:3000/flood;/flood"`

Visiting `http://<ip-of-server>/flood` gives me a blank page, but when I inspect the code I get.

```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="/flood/manifest.json"><link rel="shortcut icon" href="/flood/favicon.ico"><title>Flood</title><link href="/flood/static/css/main.7c68fbb1.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="app"></div><script type="text/javascript" src="/flood/static/js/main.1977e1fb.js"></script></body></html>
``` 

So it sort of works, but it will not show any content. Also, if I visit `http://<ip-of-server>/flood/<random>` it gives me the exact same. Ie. all URLs goes to the same place rendering the links in the HTML useless.

Any pointers on this?

EDIT:
I have set the path to /flood in the config file and recompiled flood.

Here is the config:
```
const CONFIG = {
  baseURI: '/flood/',
  dbCleanInterval: 1000 * 60 * 60,
  dbPath: '/config/flood-db/',
  floodServerHost: '0.0.0.0',
  floodServerPort: 3000,
  floodServerProxy: 'http://127.0.0.1',
  maxHistoryStates: 30,
  pollInterval: 1000 * 5,
  secret: '<redacted>,
  scgi: {
    host: 'localhost',
    port: 5000,
    socket: true,
    socketPath: '/tmp/.rtorrent.sock'
  },
  ssl: false,
  sslKey: '/config/nginx/key.pem',
  sslCert: '/config/nginx/cert.pem',
  torrentClientPollInterval: 1000 * 2
};

module.exports = CONFIG;
```

**Comment by jmarinaro** [comment] 2018-07-05 03:48
> If you're proxying Flood to a path other than the root of the host, you must specify the baseURI in config.js. All request URIs will be prefixed with this value.

**Comment by noraj** [comment] 2018-07-07 14:12
Hello @NoLooseEnds,

Thanks for posting your issue, but can you please take time to edit it in order to fill the issue template.

```markdown
## Note

- [ ] You may try to follow the update procedure described in the README and try again before opening this issue.
- [ ] Before asking for something, please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [ ] Before opening a bug issue, please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.
- [ ] If you want to contribute to the project please review the [contributing guidelines](https://github.com/jfurrow/flood/blob/master/.github/CONTRIBUTING.md).
- [ ] Keep in mind that Flood is a [FLOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software#FLOSS) (Free, Libre and Open Source Software), so please try to provide a PR when opening a bug issue. Without contributions the project can't live and with your help fix and request will come faster.
- [ ] The project is accepting issues (bugs report), feature or enhancement requests, discussions and questions but **not personal support**.

## Summary
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version:
```

I'm closing the issue until you fill it.

Feel free to ask to re-open it as soon as it's done.

PS: your problem is not a bug but seems to be a mistake in your configuration. As stated in the template flood is an open-source project running with volunteers giving their free time so I'm sorry but we have no time for free support. 

> The project is accepting issues (bugs report), feature or enhancement requests, discussions and questions but **not personal support**.

You may try the discord server on channel `#troubleshouting`.

[![Discord server badge](https://img.shields.io/discord/418267176873623553.svg?style=flat-square)](https://discord.gg/Z7yR5Uf)

**Closed by noraj** 2018-07-07 14:12 UTC
