### ISSUE TITLE
[Suggestion] Per torrent bandwidth limits

### ISSUE THREAD

**Issue by Esux** [jfurrow/flood#637] opened 2018-03-13 11:59 UTC
## Summary
Similar to rutorrents channels where you can set bandwidth limits then assign them to torrents.

Basically, I like certain torrents to use all available bandwidth where as others that would saturate the line constantly I would like to limit.

**Comment by noraj1337** [comment] 2018-03-15 00:10
Issue template was not respected and it it a duplicate of https://github.com/jfurrow/flood/issues/212

**Closed** 2018-03-15 00:09 UTC

**Comment by Esux** [comment] 2018-03-15 18:24
Not respected.. because it's not a bug?

I'm not going to submit irrelevant information. Sorry.

**Comment by noraj1337** [comment] 2018-03-15 18:32
@Esux 
1) As I said it's a duplicate so may be you didn't check existing issues.
2) Please read the template : 

```markdown
[...]
## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->
[...]
```

There are some `If suggesting a change/improvement` blocks. You can also provide a `## Possible Solution`, a `## Context`. Only `## Steps to Reproduce (for bugs)` and `## Your Environment` are not needed here. So yes please you need to respect the template.

**Comment by Esux** [comment] 2018-03-16 12:28
I checked existing issues but clearly I never used the correct term to get it to show.

Sorry, but you seem a bit elitist for no good reason. Good luck with your project though.

**Comment by noraj1337** [comment] 2018-03-16 20:43
When participating into a project you see a lot of people hit and running, just doping one sentence of 5 words to describe an issue and so project team is forced to ask one thousand questions. That's why there is a template, you fill all information from the beginning and the project team has to ask you very few questions. I'm not elitist, just trying to do it the right way and bored of people not trying hard enough to do it that way.

**Comment by jfurrow** [comment] 2018-03-17 08:24
@noraj Thank you, very much, for everything you do! 💖

@Esux I'm sorry you felt wronged, but @noraj is very generously maintaining the issue queue so that it's actually usable and not overwhelming for contributors.

**Comment by Esux** [comment] 2018-03-17 13:25
I'm not describing an issue though, am I? It's a very straight forward suggestion and doesn't really require an in depth explanation.

Your requirements if it were a bug make sense because you need as much information as possible to reproduce it.  Where as a small suggestion does not. I offered the suggestion as a consumer, not a developer.
