### ISSUE TITLE
Multi-file torrents are saved to the disk without the base path (again)

### ISSUE THREAD

**Issue by varyoo** [jfurrow/flood#506] opened 2017-10-25 17:57 UTC
Base path checked or not. Can the issue be confirmed by someone else?

**Comment by russellwilson01** [comment] 2017-10-30 21:40
Confirmed i have the same issue with Base Path selected & unselected

**Comment by dcousens** [comment] 2017-11-15 11:00
Confirmed

**Comment by noraj1337** [comment] 2017-11-27 17:58
Duplicate of issue #390

**Closed** 2017-11-28 01:11 UTC
Labels: duplicate
