### ISSUE TITLE
Flood doesn't work on OSX (and some windows browsers)

### ISSUE THREAD

**Issue by knightsg** [jfurrow/flood#471] opened 2017-10-16 04:15 UTC
I just tried out Flood today and while it initially worked fine, at some point I wasn't able to get to the overview page any more. It would accept my login credentials and then hang forever after doing the first 2 checks.

After much hair pulling I realised that the issue only happened when I tried to access Flood on a mac. I tried this on 2 different Mac laptops (running El Capitan and Sierra respectively) and on 3 different browsers (Chrome, Firefox and Safari) and it has the same problem in all of them. 

I went back to test on my windows 10 PC and it works fine in Chrome. I also tried Firefox and that worked without any issues. However I tried it in Edge and it just showed a blank grey page, didn't even take me to the login. I checked the console in Edge and it shows an error, "SCRIPT5009: 'EventSource' is undefined".

**Comment by jfurrow** [comment] 2017-10-17 04:28
@knightsg The error reporting in Flood leaves a lot to be desired, but the symptoms you're describing makes it sound like rTorrent stopped running. Can you see if the Flood server reported anything in the console?

`EventSource` is a requirement of Flood and is not supported by IE or Edge. It can be polyfilled easily, but hasn't been yet.

**Comment by knightsg** [comment] 2017-10-17 18:03
Also, something I forgot to mention initially is that when Flood hangs while loading it seems to be stuck on this particular call every time:

http://192.168.1.5:3000/api/activity-stream?historySnapshot=fiveMin

**Comment by randomnonsense** [comment] 2017-10-18 16:33
I too think issues with running anything else than Chrome/Chromium or Firefox are not important. People can easily adjust. This doesn't prevent them from using Flood at all.

**Comment by jfurrow** [comment] 2017-10-21 04:15
@knightsg I can't reproduce this and I don't think others can either. Can you share more information about your specific configuration?

**Comment by jfurrow** [comment] 2017-10-23 05:53
I'm going to close this, as it's not an issue with Flood.

**Closed by jfurrow** 2017-10-23 05:53 UTC
Labels: can't reproduce

**Comment by knightsg** [comment] 2017-10-23 16:51
Sorry, I was busy over the weekend and didn't get a chance to follow up. If I'm the only one who's experienced this issue then I concur that it's probably not worth an in-depth investigation. I'll do some more digging at my end and if I find a solution will note it here.

**Comment by wopian** [comment] 2017-10-23 17:32
For `EventSource' is undefined` see #437
